name: CI - Compile

on: [workflow_dispatch]

jobs:
  build:
    runs-on: [linux, x64, yocto]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build Yocto Rootfs
      run:  |
        source poky/oe-init-build-env .
        bitbake core-minimal-image
        
